### ISSUE TITLE
Style fixed input field

### ISSUE THREAD

**Issue by MikkelPaulson** [initiative-sh/initiative.sh#214]
Set the input field to `display: fixed`. Update margins and styling so that it still looks good when the user is not scrolled to the very bottom of the page.

**Comment by alfonsomartinezs** [comment]
Hey there! I'd like to take a crack at this issue if that's ok

**Comment by MikkelPaulson** [comment]
@alfonsomartinezs Certainly, please let me know (here or on Discord) if I can be of any help. The [developer documentation](https://github.com/initiative-sh/initiative.sh/blob/main/CONTRIBUTING.md), such as it is, is very new, so I'd also appreciate any feedback or corrections you have there.
