### ISSUE TITLE
Consolidate vocabulary for name-generators

### ISSUE THREAD

**Issue by ChrisRenfrow** [initiative-sh/initiative.sh#306]
As discussed [here](https://github.com/initiative-sh/initiative.sh/pull/305#discussion_r1111129315) and [here](https://github.com/initiative-sh/initiative.sh/issues/293#issuecomment-1432318312), a clear pattern has emerged which indicates shared vocabulary between modules would significantly reduce code reuse. It seems that it would make sense to place this new vocabulary module immediately under `world` so as to share it with all future name generators.

**Comment by ChrisRenfrow** [comment]
I'm willing to start work on this as soon as possible.

**Comment by MikkelPaulson** [comment]
Go for it!
